//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingCars.Lib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string VIN { get; set; }
        public string RegNo { get; set; }
        public Nullable<int> CustomerFK { get; set; }
        public Nullable<int> ConnectionStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
